### ISSUE TITLE
Package as .jar for mac and linux

### ISSUE THREAD

**Issue by parointi** [The-Intelligent-One/FGO-Tracker#77]
Since this is written in java, could it be easily released for mac/linux as a .jar file instead of .exe?

**Comment by The-Intelligent-One** [comment]
Ah, I didn't think about that before, since I have very little experience with running apps on linux or mac, and was really attached to the "users shouldn't need java installed" idea.

I can probably release the .jar with little effort, as soon as I get some free time (which I don't have a lot of which is why development has stagnated)

**Comment by The-Intelligent-One** [comment]
Hey, with the new (minor) release, v0.2.4, I included the .jar file too. If you have time, could you report back if it works as it should on your end too? It's fine for me on Windows at least

**Comment by parointi** [comment]
I downloaded the v0.2.4 jar and it works!

**Comment by The-Intelligent-One** [comment]
Perfect, thanks for the suggestion
